### ISSUE TITLE
Transmutation table/tablet forget learned items/blocks

### ISSUE THREAD

**Issue by zortag** [sinkillerj/ProjectE#434]
exactly what title says. learned items and blocks are randomly  forget by the table, so when you go to search for them you are not able to find them. mod's blocks are more affected than vanilla blocks. custom added blocks are the most affected. the blocks are forget whether if you reload a game, restart the game or simply the time passes.
there is a lenght to the learned item list? i'm sure the tablet once forgot cobblestone too.

**Comment by MaPePeR** [comment]
What version are you using? this was fixed some time ago.

**Comment by zortag** [comment]
ProjectE-1.7.10-0.2d-dev14.jar

**Comment by piotrb** [comment]
I had the same thing happen on version 1.1.0 

It could be related to happening after long sessions as the OP suggested or possibly something to do with EMC reloads .. since I was adding emc values for some items. (altho the forgetting is not related to those items, its forgotten even my mk3 collectors from its list).

**Comment by Kolatra** [comment]
Can someone see if this still happens at all in the latest version?

**Comment by Bersham** [comment]
As of PE 1.4.3 the problem is still persistent. I noticed that after restarting Minecraft, a random assortment of items are forgotten. Ingots/blocks/items from EnderIO; ingots/blocks/items from ExtraUtils; ingots/blocks/items from Thermal Expansion; ingots/blocks/items from BigReactors; blocks/items from ChickenChunks; blocks/items from Carpenter's Blocks; blocks/items from EnderStorage; blocks/items from Iron Chest; blocks/items from JABBA, all get removed from the Transmutation Tablet.

Also add ingots/blocks/items from Chisel 2, Modular Systems, Open Blocks/OpenMods, ProjectE, Redstone Arsenal, RemoteIO, Simply Jetpacks, Tinkers' Construct, Thermal Dynamics; Twilight Forest, Translocator, Thermal Foundation, etc.

It's all random too. Some things remain inside the Transmutation Tablet after a restart, some things don't. The good part is that the EMC value is not changing after restarting Minecraft.

My fml-client log files are about 4.3 MB, too much for pastebin or alternatives. I only have a MEGA account at the moment. Here is the link to the last few fml-client logs:

https://mega.co.nz/#F!V9hRSQYA!XbnVlq-2u-nIu1x3OdDkAA

**Comment by Kolatra** [comment]
The log files aren't providing anything sadly, it's odd how it would get lost because I would think that when you exit the game, it SHOULD save it... Something may be messing with your NBT. I've never had this problem happen myself, so I'm thinking it may be a mod interaction problem or a configuration with your specific instance.

**Comment by zortag** [comment]
I confirm what bersham wrote. it seems that oldest items are forgotten in favor of new. 
I noticed it because usually I do not find the items that I have not searched for a while. Is not a rule but that is what happens more often

**Comment by Bersham** [comment]
I'll take some time to make a clean instance with only ProjectE. After a few restarts, I'll add each mod back in one at a time. I'll get back to you guys after.

**Comment by MaPePeR** [comment]
Maybe we could use the `WorldSavedData`-Thing to write the knowledge/bags & stuff

[(Example i got from IRC #minecrafforge)](https://github.com/Questology/Questology/blob/master/src/main/java/demonmodders/questology/QuestologyWorldData.java)

**Comment by Parker8283** [comment]
Transmutation data was saved using the world save data in EE2, so it would make sense to do that here.

**Comment by Bersham** [comment]
I'm thinking now that ProjectE is not the culprit. I've tested for a while now. I've re-installed Minecraft, MinecraftForge, and ProjectE with no problems. I've re-added mods one at a time with no problems. Updates and item removals from other mods is probably the issue here, especially dev builds.

I'm not sure why vanilla Minecraft items were being removed from the transmutation tablet before, but there doesn't seem to be a problem anymore.

**Comment by Bersham** [comment]
Okay! So I think I figured out the god damn problem! I stumbled on this "bug" today. I don't know if it's a "bug" or part of the mechanics, but items are "hidden" inside the transmutation table/tablet when the EMC is too low to transmute them (i.e. having only 23,000 EMC will hide any item that needs more than 23,000 EMC to transmute). The items aren't actually deleted, at least in my world, but hidden until you have enough EMC to transmute them.

**Comment by MaPePeR** [comment]
It's not a bug, it's a feature...

**Comment by Bersham** [comment]
Yup! I sure have learned that.

**Comment by sinkillerj** [comment]
Closing duplicates of #753

**Comment by brony9tynine** [comment]
Where does the players knowledge get stored relative to the saves folder so I can just make a backup to prevent any further losses of knowledge

**Comment by williewillus** [comment]
it's in player.dat

**Comment by Metatroful** [comment]
Im playing tekkit legends on version 1.1.1
And im getting the same problem except its the new items and since they get forgotten and even if i burn off the items again to get them remembered... they wont get saved in the transmutation table or tablet.
Nothing changes even if i get rid of the table and throw it in lava, still comes back the same.
Ive got about 13.5 stacks of red matter and i cant use them on omega stars because all have been forgotten for good, creating the stars one by one takes too long so i hope there is some sort of fix to it soon or if there is already
The items that have been forgotten seem to be only above diamonds in emc value, which makes it very hard to make everything now
Ive got the stuff the make a tome of knowledge but i doubt that would help... if i could make it in the first place

![20180927_114345](https://user-images.githubusercontent.com/43627067/46118634-d911f000-c24a-11e8-806a-9a5fe7119136.jpg)

**Comment by sinkillerj** [comment]
@Metatroful You have an item in the center of your transmutation circle, thats filtering EMC, remove it...

**Comment by Metatroful** [comment]
Never knew about that thanks thought it was weird having a blank space in the middle never really pay attention to that
il try it when i get on next time

**Comment by FluffyWolf1** [comment]
So i just had a similar thing happen to me in project ozone lite the game just deleted all 3 million of my emc then unlearned every single item i made it learn any idea why?
