### ISSUE TITLE
Chisel Mapping Crash

### ISSUE THREAD

**Issue by zane49er** [sinkillerj/ProjectE#835]
I am having an issue when using other mods or custom EMC where knowledge just seems to disappear. some examples include Galacticraft, Natura, and Reactorcraft. I do not mean the entire knowledge set, just random items like lodestone or a few saplings. also, I do not know exactly what version I am using but it is from about 2 weeks ago.

**Comment by williewillus** [comment]
Please verify your exact version number, that's very important

**Comment by zane49er** [comment]
hmm, may be older than I thought... P.E.1.5.0. I will try updating.

**Comment by zane49er** [comment]
now I am having an even worse issue, where as soon ans the words "loading world" show in loading or creating a world, it kicks to the title screen without error message.

**Comment by williewillus** [comment]
Yeaaaah that's two versions old ;) the sole purpose the latest version was released was just to fix the data loss issue
That is probably another issue I know of that will be resolved in PE1.7 :D

**Comment by williewillus** [comment]
If you are still crashing in 1.7.1 post a log

**Comment by zane49er** [comment]
I am still a little bit confused... was it fixed, is it being fixed, and what about the no loading thing?

**Comment by williewillus** [comment]
Knowledge loss fixed in 1.7. No loading thing I need to see a log

**Comment by zane49er** [comment]
the log did not detect a crash, so I took out the relevant chunk: (I also removed any references to sneaky stuff I could find)
http://pastebin.com/G3qKKBiT

**Comment by zane49er** [comment]
BTW I have Fastcraft installed, which the thing says needs to be stated, though the problem seems to be chisel.

**Comment by sinkillerj** [comment]
Until a fix is released disabling Chisel in your mapping config should work around this issue.

**Comment by MaPePeR** [comment]
@zane49er which version of Chisel are you using? The mapping *should* work fine with the latest [Chisel 2 Release](http://minecraft.curseforge.com/mc-mods/225236-chisel-2/files). I tested this with `Chisel 2 - 2.4.0`.

Are you using an old Chisel 1 version?

**Comment by zane49er** [comment]
updating chisel seems to have 2 effects: my computer runs at about .01 FPS, but it is launchable.

**Comment by zane49er** [comment]
restart of computer fixed the slowness. thanks for the help, everybody

**Comment by zane49er** [comment]
now it is launchable, but I am still having the issue I started with! I am going to just cheat in a tome of knowledge.

**Comment by williewillus** [comment]
Did you update projecte?

**Comment by zane49er** [comment]
yes, in the old versions, the knowledge tome didn't even work. I also think the data for alchemical bags is being deleted.

**Comment by williewillus** [comment]
what?
ProjectE 1.7.1 is latest.
Also give me a full mod-list.
Is the bag deletion happening in the LATEST version? If so, tell me what you were doing.

**Comment by zane49er** [comment]
the bag deletion I am not exactly sure about, it definetly happened before, possibly after. I am using the latest, and most of the mod list is here: https://docs.google.com/spreadsheets/d/10h_y5lmGSB675LM55wm22VaLWqV70YepsLyBAxEmd6Q/edit?pli=1#gid=0
edits I made are:
  added:
    project E
    adv. genetics
    minecfactory reloaded
    modular powersuits
    logistics pipes
    all required cores for above stated
  updated:
    chisel

**Comment by zane49er** [comment]
when I noticed before, it was because a lot of ae, mystcraft, and logic-pipes disappeared, now I may have lost all of the birch wood in a dark forest (not a huge deal, but could've been)

**Comment by williewillus** [comment]
That really doesn't help :/ PE 1.7 was designed to stop the data loss issues so if that happens, make a separate report with fml-latest.log attached
Anyways, back to the original topic, you can load worlds now with updated chisel?

**Comment by zane49er** [comment]
yes, I can load worlds.
